### ISSUE TITLE
Unable to get property 'sign' of undefined or null reference

### ISSUE THREAD

**Issue by karikera** [Yaffle/babel-plugin-transform-bigint#6]
![image](https://user-images.githubusercontent.com/6016498/99577079-2ac6f700-2a1e-11eb-9814-f14690a59368.png)
Unable to get property 'sign' of undefined or null reference
a.a is undefined

**Comment by Yaffle** [comment]
https://github.com/Yaffle/babel-plugin-transform-bigint/commit/78dc7a4c7e5826d766ee5f6ca676369d01b0fb44
